---
# Environment
environment:
  stage: "DEVELOPMENT" # DEVELOPMENT, TEST, STAGING, PRODUCTION
  runTestEnvironment: ["LOCAL", "DEVELOPMENT", "TEST"]

# Databases
databases:
  identityDB:
    connectionName: "db-identity"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "d3ta"
    password: "d3ta"
    hostName: "127.0.0.1:3306" # hostname:port OR path
    dbName: "a_d3ta_iam"
    config: "charset=utf8&parseTime=True&loc=Local"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: true # shoud be "false" on production
  mainDB:
    connectionName: "db-main"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "d3ta"
    password: "d3ta"
    hostName: "127.0.0.1:3306" # hostname:port OR path
    dbName: "a_d3ta_data"
    config: "charset=utf8&parseTime=True&loc=Local"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: true # shoud be "false" on production

# Indexers
indexers:
  dataIndexer:
    connectionName: "data-indexer"
    engine: "elasticsearch"
    driver: "elasticsearch"
    version: "7"
    configurations:
      adapter: "elasticsearch"
      addresses:
        - "http://localhost:9200"
        - "http://localhost:9201"
      username: ""
      password: ""
      cloudID: ""
      APIKey: ""
  logIndexer:
    connectionName: "log-indexer"
    engine: "elasticsearch"
    driver: "elasticsearch"
    version: "8"
    configurations:
      adapter: "elasticseach"
      addresses:
        - "http://localhost:9201"
        - "http://localhost:9200"
      username: ""
      password: ""
      cloudID: ""
      APIKey: ""
